services:
  mcp:
    build:
      context: .
    entrypoint: [ "webquest-mcp" ]
    environment:
      - WEBQUEST_MCP_AUTH_SECRET
      - WEBQUEST_MCP_AUTH_AUDIENCE
      - WEBQUEST_MCP_TRANSPORT=streamable-http
      - WEBQUEST_MCP_HOST=0.0.0.0
      - WEBQUEST_MCP_PORT=8000
      - HYPERBROWSER_API_KEY
      - OPENAI_API_KEY
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          initial_sync: true
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
  ngrok:
    image: ngrok/ngrok:latest
    command: http mcp:8000
    environment:
      - NGROK_AUTHTOKEN
    depends_on:
      - mcp
    ports:
      - "4040:4040"
  test:
    build:
      context: .
      args:
        UV_NO_DEV: 0
    depends_on:
      - ngrok
    environment:
      - TEST_ACCESS_TOKEN
      - TEST_SERVER_URL
      - OPENAI_API_KEY
    entrypoint: [ "python", "tests/test_client.py" ]
    profiles: [ "test" ]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          initial_sync: true
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
